# ignored options for 'duplicati'
# --detach
version: "3.3"
services:
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:latest
    hostname: duplicati
    environment:
      - PUID=0
      - PGID=0
      - CLI_ARGS= #optional
      - TZ=Asia/Shanghai
      - LANGUAGE=ch_ZN.UTF-8
    volumes:
      - ${ENV_DIR_BACKUPS}:/backups
      - ${ENV_DIR_CONFIG:-./config}:/config
    privileged: true
    ports:
      - 8200:8200
    restart: always
    env_file:
      - .env