- name: Refresh server ip address
  hosts: localhost
  gather_facts: false
  connection: local

  # vars:
    # token: "do://AccessToken?hostname=x"
    # token : "aws://AccessKeyID:AccessSecretKey@RegionName?hostname=x"

  tasks:
    - name: Import aws ec2 tasks
      ansible.builtin.include_tasks: "../tasks/aws-ec2.yaml"
      vars:
        aws_token: "{{ token }}"
        aws_uptime: 10
      when: token | urlsplit("scheme") == 'aws'

    - name: Import do droplets tasks
      ansible.builtin.include_tasks: "../tasks/digitalocean-droplets.yaml"
      vars:
        do_token: "{{ token }}"
      when: token | urlsplit("scheme") == 'do'
