version: "3"
services:
  chinesesubfinder:
    container_name: chinesesubfinder
    image: allanpk716/chinesesubfinder:latest
    hostname: chinesesubfinder
    environment:
      - PUID=0         # uid
      - PGID=0          # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    volumes:
      - ${ENV_DIR_CONFIG:-./config}:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - ${ENV_DIR_MEDIA:-./media}./media:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - ${ENV_DIR_CACHE:-./cache}:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    privileged: true
    ports:
      - 9035:19035
      - 9037:19037
    restart: always
    env_file:
      - .env