version: "3"
services:
  ssserver:
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    container_name: ssserver
    volumes:
      - ./config:/app/data
    command:
      - sh
      - -c
      - ssserver --log-without-time -a nobody -c /etc/shadowsocks-rust/config.json
    environment:
      - ENV_SS_PASSWORD=password # ss password
    network_mode: host
    restart: always