version: "3"
services:
  memos:
    container_name: memos
    image: neosmemo/memos:latest
    hostname: memos
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 5230:5230
    restart: always
    networks:
      - all-connection
networks:
  all-connection:
    external: true