version: "3"
services:
  memos:
    container_name: memos
    image: neosmemo/memos:latest
    hostname: memos
    volumes:
      - ${ENV_DIR_DATA:-./data}:/var/opt/memos
    ports:
      - 5230:5230
    restart: always
    env_file:
      - .env