version: "3"
services:
  newfuture_ddns:
    image: newfuture/ddns:latest
    container_name: ddns
    environment:
      - DDNS_DNS=${ENV_DNS_PROVIDER}
      - DDNS_ID=${ENV_DNS_PROVIDER_ID}
      - DDNS_TOKEN=${ENV_DNS_PROVIDER_TOKEN}
      - DDNS_IPV4=${ENV_HOST}
      - DDNS_IPV6=${ENV_HOST}
      - DDNS_INDEX4=shell:wget -q -O - ipv4.ip.sb
      - DDNS_INDEX6=shell:wget -q -O - ipv6.ip.sb
    network_mode: host
    restart: always
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${ENV_WORKDIR}/nginx-proxy-manager/data:/data
      - ${ENV_WORKDIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: always
    extra_hosts:
      - ${ENV_HOST}:host-gateway
  ssserver:
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    container_name: ssserver
    command:
      - sh
      - -c
      - apk add curl >> /dev/null && curl -s -o
        /etc/shadowsocks-rust/config.json ${ENV_SS_CONFIG_FILE_URL} &&ssserver
        --log-without-time -a nobody -c /etc/shadowsocks-rust/config.json
    environment:
      - ENV_SS_PASSWORD=${ENV_SS_PASSWORD}
    network_mode: host
    restart: always
networks: {}