version: "3"
services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ${ENV_WORKDIR}/semaphore/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - ${ENV_WORKDIR}/semaphore/playbook:/opt/semaphore/
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /opt/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ENV_ADMIN_USER}
      SEMAPHORE_ADMIN: ${ENV_ADMIN_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENV_ADMIN_TOKEN}
    depends_on:
      - mysql
networks: {}
