version: "3"
services:
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - ${ENV_WORKDIR}/semaphore/playbook:/opt/semaphore/
      - ${ENV_WORKDIR}/semaphore/data/lib:/var/lib/semaphore
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_PLAYBOOK_PATH: /opt/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ENV_ADMIN_USER}
      SEMAPHORE_ADMIN: ${ENV_ADMIN_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENV_ADMIN_TOKEN}
      TZ: Asis/Shanghai
