version: "3"
services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - ${ENV_DIR_PLAYBOOK:-./playbook}:/opt/semaphore/
      - ${ENV_DIR_DATA:-./data/lib}:/var/lib/semaphore
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_PLAYBOOK_PATH: /opt/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ENV_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ENV_ADMIN_USER}
      SEMAPHORE_ADMIN: ${ENV_ADMIN_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENV_ADMIN_TOKEN}
      TZ: Asis/Shanghai
    restart: always
    env_file:
      - .env