version: "3"
services:
  gitea:
    container_name: gitea
    hostname: gitea
    image: gitea/gitea:latest
    volumes:
      - ./data:/data
    ports:
      - 10022:22
      - 3001:3000
    restart: always
    env_file:
      - .env
  act_runner:
    container_name: gitea_runner
    image: gitea/act_runner:latest
    hostname: gitea_runner
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=${GITEA_RUNNER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - .env