version: "3"
services:
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce
    hostname: portainer
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 8000:8000
      - 9000:9000
      - 9996:9996
    restart: always
    networks:
      - all-connection
networks:
  all-connection:
    external: true
