version: "3"
services:
  newfuture_ddns:
    image: newfuture/ddns:latest
    container_name: ddns
    environment:
      - DDNS_DNS=${ENV_DNS_PROVIDER}
      - DDNS_ID=${ENV_DNS_PROVIDER_ID}
      - DDNS_TOKEN=${ENV_DNS_PROVIDER_TOKEN}
      - DDNS_IPV4=${ENV_HOST}
      - DDNS_IPV6=${ENV_HOST}
      - DDNS_INDEX4=shell:wget -q -O - ${ENV_URL_IPV4_API}
      - DDNS_INDEX6=shell:wget -q -O - ${ENV_URL_IPV6_API}
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    restart: always
    env_file:
      - .env