version: "3"
services:
  sslocal:
    image: ghcr.io/shadowsocks/sslocal-rust:latest
    container_name: sslocal
    ports:
      - 11080:11080/tcp
      - 11081:11081/tcp
    volumes:
      - ./config:/etc/shadowsocks-rust
    command:
      - sh
      - -c
      - sslocal --log-without-time -a nobody -c /etc/shadowsocks-rust/config.json
    restart: always
    networks:
      - all-connection
networks:
  all-connection:
    external: true
