version: "3"
services:
  neko:
    image: ghcr.io/m1k1o/neko/intel-microsoft-edge:latest
    restart: unless-stopped
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8089:8080
      - 52000-52100:52000-52100/udp
    environment:
      NEKO_SCREEN: 1280x720@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: xxx.xxx.xxx.xxx
      NEKO_FILE_TRANSFER_ENABLED: true # changeme
      NEKO_ICELITE: 1
  coturn:
    image: coturn/coturn:latest
    network_mode: host
    command: |
      -n
      --realm=localhost
      --fingerprint
      --listening-ip=0.0.0.0
      --external-ip=xxx.xxx.xxx.xxx
      --listening-port=3478
      --min-port=49160
      --max-port=49200
      --log-file=stdout
      --user=neko:neko
      --lt-cred-mech
networks: {}
