version: "3"
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Shanghai
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ./config:/config
      - ./data:/data
      - ./downloads:/downloads
    ports:
      - 8085:8080
    restart: always
    env_file:
    networks:
      - all-connection
networks:
  all-connection:
    external: true