- name: Install 1panel
  ansible.builtin.shell: |
    curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh
    expect << EOF
      set timeout 300
      spawn bash quick_start.sh
      expect "/opt"
      send "{{ work_dir }}\n"
      expect "1Panel 端口"
      send "{{ panel_port }}\n"
      expect "1Panel 面板用户"
      send "{{ panel_user }}\n"
      expect "1Panel 面板密码"
      send "{{ panel_password }}\n"
      expect "#"
      exit 0
    EOF
  args:
    creates: /usr/local/bin/1panel
  become: true
  changed_when: false

- name: Show 1panel 1panel user info
  ansible.builtin.shell: |
    1pctl user-info
  become: true
  changed_when: false
