- name: Parse input token
  ansible.builtin.set_fact:
    do_query_keys: '{{ do_token | urlsplit("query") | regex_findall("(?<=&|\?)(.+?)(?==)") }}'
    do_query_values: '{{ do_token | urlsplit("query") | regex_findall("(?<==)(.+?)(?=&|#|$)", multiline=True) }}'
- name: Parse input token
  ansible.builtin.set_fact:
    do_oauth_token: '{{ do_token | urlsplit("hostname") }}'
    do_parameters: '{{ dict( do_query_keys | ansible.builtin.zip(do_query_values)) }}'
  vars:
    do_query_keys: '{{ do_token | urlsplit("query") | regex_findall("(?<=\?|&)(.+?)(?==)") }}'
    do_query_values: '{{ do_token | urlsplit("query") | regex_findall("(?<==)(.+?)(?=&|#|$)", multiline=True) }}'
- debug:
    var: do_query_values
- name: Exit process
  ansible.builtin.fail:
    msg: |
      The input token
        do_oauth_token = {{ do_oauth_token }}
      doesn't match the format
  when: do_oauth_token == ""